
---

spring:
  profiles: default
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
app:
  creditLimit: 10
  positiveAmountNeededForCredit: 5
  amountChergedBy15Min: 1
  
---

spring:
  profiles: integration
  datasource:
    url: jdbc:h2:mem:integrationdb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
app:
  creditLimit: 10
  positiveAmountNeededForCredit: 5
  amountChergedBy15Min: 1
